// Prompt-commits synthesis: turn a staged diff into the prompt that would
// regenerate it, used as the commit message. This mirrors how
// `coverage/run.ts` builds the sync prompt — the action-prompt is assembled
// in the renderer (it varies per commit), while the agent's system prompt
// stays put in the harness.
//
// The model returns subject + body only (the reconstructable spec). The
// caller appends provenance trailers so they are asserted by the app, not
// the model — see buildTrailers / CommitContext.

export interface CommitMessage {
  subject: string
  body: string
}

// Guardrail: a diff this large blows past a useful context window and almost
// always means the user staged a generated/vendored blob. We truncate and
// tell the model so it doesn't pretend to have seen the whole thing.
const MAX_DIFF_CHARS = 60_000

export function buildCommitSynthesisPrompt(diff: string): string {
  let body = diff
  let truncatedNote = ''
  if (diff.length > MAX_DIFF_CHARS) {
    body = diff.slice(0, MAX_DIFF_CHARS)
    truncatedNote =
      '\n\n[diff truncated for length — describe intent from what is shown and note that some changes were not visible]'
  }

  return [
    'You are writing a git commit message for the staged diff below. The message IS the prompt that would let a competent engineer (or AI agent) regenerate equivalent code from scratch — capture intent and behavior, not a line-by-line restatement of the diff.',
    '',
    'Rules:',
    '- Subject line: imperative mood, <= 72 chars, no trailing period.',
    '- Body: describe WHAT the change accomplishes and WHY, precisely enough to reconstruct equivalent code. Prefer behavior and contracts over naming every symbol.',
    '- SCRUB SECRETS: never echo API keys, tokens, passwords, connection strings, or personal data that appear in the diff. Describe their role generically (e.g. "the Stripe API key") instead of reproducing the value.',
    '- Do NOT invent changes that are not in the diff. Do NOT add trailers, sign-offs, or "Generated by" lines — those are added separately.',
    '- Output ONLY the commit message, wrapped exactly between <commit> and </commit> markers, with a blank line between subject and body.',
    '',
    'Example shape:',
    '<commit>',
    'Add refund idempotency guard to billing charge flow',
    '',
    'Make the refund path safe to retry. Look up any prior refund by',
    'idempotency key before issuing a new one; return the existing refund',
    'if found, and 409 when the key is reused with a different amount.',
    '</commit>',
    '',
    'Staged diff:',
    '```diff',
    body,
    '```' + truncatedNote
  ].join('\n')
}

// Pulls the commit message out of the model's reply. Tolerant of the model
// wrapping in markers, code fences, or neither.
export function parseCommitMessage(raw: string): CommitMessage {
  let text = raw.trim()

  const marked = text.match(/<commit>\s*([\s\S]*?)\s*<\/commit>/i)
  if (marked) {
    text = marked[1].trim()
  } else {
    // Strip a single wrapping ``` fence if present.
    const fenced = text.match(/^```[a-z]*\n([\s\S]*?)\n```$/i)
    if (fenced) text = fenced[1].trim()
  }

  const lines = text.split(/\r?\n/)
  const firstIdx = lines.findIndex((l) => l.trim().length > 0)
  if (firstIdx === -1) return { subject: '', body: '' }
  const subject = lines[firstIdx].trim().replace(/\.$/, '')
  const body = lines
    .slice(firstIdx + 1)
    .join('\n')
    .trim()
  return { subject, body }
}

export interface CommitContext {
  // Whether the coverage gate passed (always true at commit time, but kept
  // explicit so the trailer never lies).
  coveragePassed: boolean
}

// Provenance trailers the app asserts about every synthesized commit. Kept
// minimal in phase 1 — model id and session ids land with phase 2 session
// enrichment.
export function buildTrailers(ctx: CommitContext): string {
  return [
    'Codeswim-Synthesized: true',
    `Codeswim-Coverage: ${ctx.coveragePassed ? 'pass' : 'unknown'}`
  ].join('\n')
}

// Final commit body = the synthesized spec + a blank line + trailers.
export function composeCommitBody(spec: string, ctx: CommitContext): string {
  const trailers = buildTrailers(ctx)
  return spec.trim() ? `${spec.trim()}\n\n${trailers}` : trailers
}
